export const commandProjects = [
  {
    id: "id-1",
    label: "Ice cream",
    link: "https://vitalii-skubii.github.io/icecream/",
    repo: "https://github.com/vitalii-skubii/icecream/",
    // preview: iceCreamImg,
    info: "Responsive web page layout from the brand ICECREAM.",
    technology: [
      { id: "id-1", name: "HTML5" },
      { id: "id-2", name: "SCSS" },
      { id: "id-3", name: "JavaScript" },
      { id: "id-4", name: "Parcel" },
    ],
  },
  {
    id: "id-2",
    label: "Project planning",
    link: "https://project-planning.netlify.app/",
    repo: "https://github.com/OlenaTsemko/project-planning-rest-api",
    // preview: projectPlanningImg,
    info: "Project Planning is a full-stack application that will allow you to effectively manage your time.",
    technology: [
      { id: "id-1", name: "React" },
      { id: "id-2", name: "React Hooks" },
      { id: "id-3", name: "React Router" },
      { id: "id-4", name: "Code Splitting" },
      { id: "id-5", name: "Redux " },
      { id: "id-6", name: "Axios" },
      { id: "id-7", name: "Material Ui" },
      { id: "id-8", name: "React chart.js 2" },
      { id: "id-9", name: "Node.js" },
      { id: "id-10", name: "MongoDB" },
      { id: "id-11", name: "Mongoose" },
    ],
  },
];

export const ownProjects = [
  {
    id: "id-1",
    label: "Web Studio",
    link: "https://vadim-vatrya.github.io/goit-markup-hw-08/",
    repo: "https://github.com/Vadim-Vatrya/goit-markup-hw-08",
    // preview: webStudioImg,
    info: "Layout of a web page.",
    technology: [
      { id: "id-1", name: "HTML5" },
      { id: "id-2", name: "SCSS" },
      { id: "id-3", name: "Parcel" },
    ],
  },
  {
    id: "id-2",
    label: "Image Finder",
    link: "https://vadim-vatrya.github.io/goit-js-hw-13-image-finder",
    repo: "https://github.com/Vadim-Vatrya/goit-js-hw-13-image-finder",
    // preview: imageFinderImg,
    info: "Adaptive web-page with image search by keywords.",
    technology: [
      { id: "id-1", name: "HTML5" },
      { id: "id-2", name: "CSS3" },
      { id: "id-3", name: "React" },
      { id: "id-4", name: "AJAX" },
      { id: "id-5", name: "REST API" },
      { id: "id-6", name: "Axios" },
    ],
  },
  {
    id: "id-3",
    label: "Movies",
    link: "https://vadim-vatrya-goit-react-hw-04-movies.netlify.app/",
    repo: "https://github.com/Vadim-Vatrya/goit-react-hw-04-movies",
    // preview: moviesImg,
    info: "App for watching popular and searching films. The application uses themoviedb.org API.",
    technology: [
      { id: "id-1", name: "HTML5" },
      { id: "id-2", name: "CSS3" },
      { id: "id-3", name: "React" },
      { id: "id-4", name: "AJAX" },
      { id: "id-5", name: "REST API" },
      { id: "id-6", name: "React-Router" },
      { id: "id-7", name: "React hooks" },
      { id: "id-7", name: "Module CSS" },
      { id: "id-8", name: "React JSS" },
    ],
  },
  {
    id: "id-4",
    label: "PhoneBook",
    link: "https://https://vadim-vatrya-goit-react-hw-09-phonebook.netlify.app",
    repo: "https://github.com/Vadim-Vatrya/goit-react-09-phonebook",
    // preview: phoneBookImg,
    info: "Phonebook application with the ability to register users and work with private collections of contacts.",
    tech: [
      { id: "id-1", name: "HTML5" },
      { id: "id-2", name: "CSS3" },
      { id: "id-3", name: "React.js" },
      { id: "id-4", name: "React-Router" },
      { id: "id-5", name: "React-Hook" },
      { id: "id-6", name: "Redux" },
      { id: "id-5", name: "AJAX" },
      { id: "id-6", name: "REST API" },
      { id: "id-7", name: "Axios" },
      { id: "id-8", name: "Material-UI" },
      { id: "id-9", name: "React JSS" },
    ],
  },
  {
    id: "id-1",
    label: "My-rezume",
    link: "https://vadim-vatrya.github.io/my-rezume",
    repo: "https://https://github.com/Vadim-Vatrya/goit-react-hw-09-phonebook",
    // preview: myRezumeImg,
    info: "Responsive web page layout from the brand ICECREAM.",
    technology: [
      { id: "id-1", name: "React" },
      { id: "id-2", name: "React JSS" },
      { id: "id-3", name: "React-Router" },
    ],
  },
];
